### ISSUE TITLE
Do you have benchmark codes in your baseline except HGG 

### ISSUE THREAD

**Issue by erdiphd** [jayLEE0301/outpace_official#1]
Hi
Do you have the benchmarks codes in your repository ?

In the paper, you compare your results with 7 different benchmarks.
![image](https://github.com/jayLEE0301/outpace_official/assets/81103451/2fb28b03-d5ce-43eb-a08b-21067790b20a)

Do you have all of them in your repository If someone wants to reproduce the result. 

Thank you

**Comment by jayLEE0301** [comment]
The HGG option in our code does not mean the HGG baseline. (We just utilize it as a goal sampling method.)
Please refer to the following repositories to run the baselines.

• HGG (Ren et al., 2019): We follow the default setting in the original implementation from https://github.com/Stilwell-Git/Hindsight-Goal-Generation.
• CURROT (Klink et al., 2022): We follow the default setting in the original implementation from https://github.com/psclklnk/currot.
• GoalGAN (Florensa et al., 2018), PLR (Jiang et al., 2021), VDS (Zhang et al., 2020), ALP-GMM (Portelas et al., 2020): We follow the default setting in implementation from https://github.com/psclklnk/currot.
• SkewFit (Pong et al., 2019): We follow the state-based version of SkewFit. The original implementation was modified and used since only the image-based version is provided in it. (https://github.com/rail-berkeley/rlkit)

**Comment by erdiphd** [comment]
Thanks for the answer. 
May I ask how did you draw this figures ?
Do you have some codes for that (or any temporary codes you used )
![image](https://github.com/jayLEE0301/outpace_official/assets/81103451/d7ba4a93-19f9-4454-81ff-ebeaad4d8862)

**Comment by jayLEE0301** [comment]
To draw that images, we first saved the curriculum goals as *.npy, and utilized plt.scatter function.

```python
import numpy as np
import os
from os.path import join as ospj
import matplotlib.pyplot as plt
import pickle
import pandas as pd
EXPRIMENT_PATH = "???????" 
DRAW_CYCLE = 8000


plt.nipy_spectral()
plt.figure()

curriculum = []
x = []
y = []

for i in range(0, DRAW_CYCLE, 25):
    data = pd.read_pickle(ospj(EXPRIMENT_PATH, '{}.pkl'.format(i)))
    for j in range(len(data)):
        x.append(data[j, 0])
        y.append(data[j, 1])
        curriculum.append(i)

plt.scatter(x =x, y = y, c = curriculum, s=5)
plt.colorbar()
plt.savefig("curriculum_goal.png")
plt.close()
```

**Comment by erdisayar** [comment]
I installed the meta world package for sawyer_push and sawyer_pickandplace in the hgg code but but somehow  the agents didn't learn.

Then I tried to implement the hgg algorithm in your repository. I just basically deleted the many lines in your script [hgg.py](https://github.com/jayLEE0301/outpace_official/blob/main/hgg/hgg.py) and implement the hgg algorithm. In this case, hgg somehow couldn't generate the intermediate goals to guide the robotic agents towards the desired goal.


Do you have the hgg code which you implemented sawyer environments ?  I am going to also cite your paper in my paper If I run the hgg with your algorithm.

Thanks a lot.

**Comment by erdiphd** [comment]
I installed the meta world package for sawyer_push and sawyer_pickandplace in the hgg code but but somehow the agents didn't learn.

Then I tried to implement the hgg algorithm in your repository. I just basically deleted the many lines in your script [hgg.py](https://github.com/jayLEE0301/outpace_official/blob/main/hgg/hgg.py) and implement the hgg algorithm. In this case, hgg somehow couldn't generate the intermediate goals to guide the robotic agents towards the desired goal.

Do you have the hgg code which you implemented sawyer environments ? I am going to also cite your paper in my paper If I run the hgg with your algorithm.

Thanks a lot.
